### ISSUE TITLE
How to get the 'kitchen-mixed-v0.py' ?

### ISSUE THREAD

**Issue by whiteBerryJ** [clvrai/spirl#22] opened 2022-03-08 02:18 UTC
Hello! 

When i run this code,

> python3 spirl/rl/train.py --path=spirl/configs/hrl/kitchen/spirl_cl --seed=0 --prefix=SPIRL_kitchen_seed0

Then i got this key error.

> completed_subtasks = info.pop("completed_tasks")
> KeyError: 'completed_tasks'

So, i commented it out and ran the code.
It went well up to 7%. (Train Epoch: 0 [It 100001/1500000 (7%)])
But this error occured.

> ValueError: tile cannot extend outside image

That means i can't render from the environment.
The reason is that there is no file named 'kitchen-mixed-v0'
How to get the 'kitchen-mixed-v0'? 
I know the code that download the offline env file but i think it doesn't opperate.

Here is my directory of the project folder.
./spirlProject
├── d4rl
│   ├── AdditionalMaps_0.9.8
│   │   ├── CarlaUE4
│   │   └── Engine
│   ├── CARLA_0.9.8
│   │   ├── CarlaUE4
│   │   ├── Engine
│   │   ├── HDMaps
│   │   ├── Import
│   │   ├── PythonAPI
│   │   └── Tools
│   ├── d4rl
│   │   ├── carla
│   │   ├── carla__
│   │   ├── flow
│   │   ├── gym_bullet
│   │   ├── gym_minigrid
│   │   ├── gym_mujoco
│   │   ├── hand_manipulation_suite
│   │   ├── kitchen
│   │   ├── locomotion
│   │   ├── pointmaze
│   │   ├── pointmaze_bullet
│   │   ├── __pycache__
│   │   └── utils
│   ├── d4rl.egg-info
│   ├── flow
│   │   ├── benchmarks
│   │   ├── controllers
│   │   ├── core
│   │   ├── envs
│   │   ├── multiagent_envs
│   │   ├── networks
│   │   ├── __pycache__
│   │   ├── renderer
│   │   ├── scenarios
│   │   ├── utils
│   │   └── visualize
│   ├── flow222
│   │   ├── docs
│   │   ├── examples
│   │   ├── scripts
│   │   ├── tests
│   │   └── tutorials
│   └── scripts
│       ├── generation
│       └── reference_scores
├── data
├── docs
│   └── resources
│       ├── env_videos
│       └── policy_videos
├── experiments
│   ├── hrl
│   │   └── kitchen
│   └── skill_prior_learning
│       └── kitchen
├── spirl
│   ├── components
│   │   └── __pycache__
│   ├── configs
│   │   ├── data_collect
│   │   ├── default_data_configs
│   │   ├── hrl
│   │   ├── rl
│   │   └── skill_prior_learning
│   ├── data
│   │   ├── block_stacking
│   │   ├── kitchen
│   │   ├── maze
│   │   ├── office
│   │   └── __pycache__
│   ├── models
│   │   └── __pycache__
│   ├── modules
│   │   └── __pycache__
│   ├── __pycache__
│   ├── rl
│   │   ├── agents
│   │   ├── components
│   │   ├── envs
│   │   ├── policies
│   │   └── utils
│   └── utils
│       ├── __pycache__
│       └── scripts
└── venv
    ├── bin
    └── lib
        └── python3.8

Are the d4rl or flow path wrong?

**Comment by kpertsch** [comment] 2022-03-08 18:54
Hi! 

Please make sure that you are installing our fork of the D4RL repo (see link in the README).
If you check the closed issues here, other people had trouble with the missing "completed_task" key too since they installed the original D4RL repo and it got resolved once they switched to our fork.

Hope this helps!

**Comment by whiteBerryJ** [comment] 2022-03-10 02:43
I added this line to kitchen.py

> env_info['completed_tasks'] = set(self.TASK_ELEMENTS) - set(self.tasks_to_complete)

Then, it works but this error occured again.

> ValueError: tile cannot extend outside image

I asked above,

> It went well up to 7%. (Train Epoch: 0 [It 100001/1500000 (7%)])
> But this error occured.
> That means i can't render from the environment.
> The reason is that there is no file named 'kitchen-mixed-v0'
> How to get the 'kitchen-mixed-v0'?
> I know the code that download the offline env file but i think it doesn't opperate.
![image](https://user-images.githubusercontent.com/56008049/157577742-24963904-2c7d-4194-8cbe-b2b12fb9d820.png)

I installed the D4RL your fork, but it can't find the environment i think.
Is the current d4rl installation directory correct?

**Comment by kpertsch** [comment] 2022-03-10 03:52
I have not seen the rendering error before, but I would hope that it too would be fixed by switching to our fork of the D4RL repo.

For the installation of our fork, please make sure that the `dm_control` package is installed (via `pip3 install dm_control`). If this package is missing the `__init__.py` file in the D4RL repo skips registering the kitchen environments.

Once you installed our fork and the dm_control package, you can test whether the installation is working by opening a python3 terminal, and testing:
```
import gym
import d4rl
gym.make("kitchen-mixed-v0")
```
If this does not throw an error the installation is correct.

**Comment by whiteBerryJ** [comment] 2022-03-10 07:24
Thank you for respned.
When i run the code, this error occured..
![image](https://user-images.githubusercontent.com/56008049/157609737-8e9c30bf-9bf4-4aeb-beac-377f446a05ed.png)

Do you know about TimeLimit error?

**Comment by kpertsch** [comment] 2022-03-10 18:11
The `TimeLimit` is not an error, it's a gym wrapper that terminates an episode automatically after a certain number of steps -- so this is intended behavior and your code seems to be working without errors.

If this is now using our D4RL fork, can you rerun the SPiRL code and see whether you still get the rendering error.

**Comment by whiteBerryJ** [comment] 2022-03-11 00:52
I tried this code.

> python3 spirl/rl/train.py --path=spirl/configs/hrl/kitchen/spirl_cl --seed=0 --prefix=SPIRL_kitchen_seed0

but i met the same trouble.
https://github.com/clvrai/spirl/issues/22#issuecomment-1063595614

So, i changed some code in rl/train.py
In "val" and "generate_rollouts" function, i changed this "sample_episode(is_train=False, **render=True**)" 
to this. "sample_episode(is_train=False, **render=False**)"
And then it trained without problem.
Do you have an idea for this?

**Comment by whiteBerryJ** [comment] 2022-03-14 04:15
Oh, it works when i reinstalled d4rl.
The remaining problem is 'Failed to initialize OpenGL ' problem

**Closed** 2022-03-15 00:47 UTC
